### ISSUE TITLE
Out-of-bounds state factor from zero-probability factored transition function

### ISSUE THREAD

**Issue by b-adkins** [MADPToolbox/MADP#10]
I had a bit of a hard time debugging a factored transition function in a custom FactoredMMDPDiscrete. I think some defensive programming would be helpful to catch the error.

In my case, I had a few state factors-action combinations where the transition function values did not sum to one - instead, every value was zero! This meant that, by the sampling method used in conditional probability table:
```c++

Index CPT::Sample(Index y) const
{
    double randNr=rand() / (RAND_MAX + 1.0);
    double cumprob = 0.0;
    Index x;
    for(x=0; x < nrX(); x++)
    {
        cumprob += _m_probTable(x,y);
        if(randNr<=cumprob)
            break;
    }  
    return(x);   
}
```

... I inevitably end up with out-of-bounds state factors that crashed the program with an out-of-bounds state. This was not caught at the state factor level.

Digging a little further, it looks like CPTs do have a sanity check function - does the whole row add up to 1.0? - but I can understand why you wouldn't use it on a factored state space. Too big, not fully defined.

Thus, it seems to me like the best way to add some defensive programming would be assert statements to catch out-of-bounds state factors during development. I'm thinking they could be compiled out unless the -DDEBUG_2DBN flag is set. It would cover cases where you can't run CPT::SanityCheck().

**Comment by oliehoek** [comment]
yes, that does sound as a sensible thing to do. I would welcome that.
