### ISSUE TITLE
missing aclocal-1.14

### ISSUE THREAD

**Issue by laurimi** [MADPToolbox/MADP#2]
This affects (at least) users running Ubuntu 16.04 Xenial Xerus, with madp-v0.4. The automake toolchain has updated to 1.15, and while following the MADP installation instruction an error is encountered similar to

`WARNING: 'aclocal-1.14' is missing on your system.`
after this, the build process is terminated.

The issue can be worked around by running again autogen.sh in the MADP directory, e.g.
`sh autogen.sh`

After this, the installation steps as in the README file seem to work.

**Comment by oliehoek** [comment]
Hi,

I guess I am confused about this a bit: I was under the impression that
the release was configured such that this was not needed... (since it
already contains a 'configure' script), and we never had people report
this before. Does this also happen when downloading and compiling the
.tar.gz file? Or only when cloning from the repos?

Best,
-Frans

**Comment by laurimi** [comment]
Hi Frans!
I can confirm that this only takes effect if you clone from the repo.

Output when cloning from the repo:

`mkdir sandbox && cd sandbox`
`git clone https://github.com/MADPToolbox/MADP.git`
`./configure --prefix=$HOME/sandbox/`
`make`

The error:

```
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /informatik2/cv/home/lauri/sandbox/MADP/missing aclocal-1.14 -I m4
/informatik2/cv/home/lauri/sandbox/MADP/missing: line 81: aclocal-1.14: command not found
WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:374: recipe for target 'aclocal.m4' failed
make: *** [aclocal.m4] Error 127
```

I tried also downloading the .tar.gz. After extracting the files:

`./configure --prefix=$HOME/sandbox/`
`make`

This way, it does start compiling!

BR,
Mikko

**Comment by oliehoek** [comment]
I have added "autogen.sh" to the repository. In cases that this affect you, you can run this ("sh autogen.sh") and it should reconfigure the required files.
