### ISSUE TITLE
Number of Agent

### ISSUE THREAD

**Issue by akouSDN** [MADPToolbox/MADP#3]
Hi all,

I have one question concerning the maximum number of agents that can MADP toolbox support ?

Best Regards,

**Comment by oliehoek** [comment]
In general, there is no real inherent maximum, but
-some algorithms (e.g., DP-LPC) only work for 2 agents
-much of the functionality does depend on enumerating concepts as such
as 'joint actions'. The default data type for this is size_t which
therefore puts a limit on the number of joint actions you could consider.

Best,
-Frans

**Comment by akouSDN** [comment]
Ok thank you much @oliehoek
