### ISSUE TITLE
Install with optional packages

### ISSUE THREAD

**Issue by JFan2016** [MADPToolbox/MADP#4]
Hi,

I am trying to add optional software following the instructions. But --with-PACKAGE and CPLEX options are unrecognized. 
configure: error: unrecognized option: `-I/opt/ibm/ILOG/CPLEX_Studio1263/cplex/include/'

Thank you!
JIng

**Comment by oliehoek** [comment]
Dear Jing,

Can you explain exactly what version of MADP you are using (version?
.tar.gz or from git?) and exactly what commands you used?

Best,
-Frans
