### ISSUE TITLE
Record traces of s->a->s->a... during Simulation?

### ISSUE THREAD

**Issue by b-adkins** [MADPToolbox/MADP#9]
For a project I am working on, we want to work with traces through time of state -> joint action -> state -> joint action. Would you guys accept a pull request that modifies SimulationResult and Simulation to also save these traces (at least for finite horizons)?

(Thanks so much for your open-source work! Exploring MADP has been a crash course in MDP variants for me!)

**Comment by oliehoek** [comment]
Sure - I suppose that could be useful. I also assume it could be a 
memory hogg, so perhaps it should not be a default option...?

You're welcome! (Good to hear it is useful!)
-Frans
